name: Build
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install docker
        run: >
          sudo apt update -y -qqq;
          sudo apt autoremove --purge needrestart || true 
          sudo apt install -y bash;
          sudo ln -svf bash /bin/sh;
          sudo /bin/bash scripts/.clean-os.sh;
          sudo /bin/bash scripts/install_for_docker.sh;
          sudo /bin/bash scripts/install_docker.sh;

      - name: Build ub2204 prerequisite
        run: |
          sudo /bin/bash run-build-ub2204.sh
          sudo /bin/systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/*
      - name: Upload ub2204 prerequisite
        run: |
          _dateutc=$(date -u +%Y-%m-%d-%H%M)
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          sudo /bin/ls -lah /home/.tmp/
          sudo /bin/ls -1 /home/.tmp/ 2>/dev/null | xargs --no-run-if-empty -I '{}' sudo /bin/bash scripts/.upload_file_to_github-release.sh --token ${{ secrets.GITHUB_TOKEN }} --user "${{ github.repository_owner }}" --repo "${_repo}" --file "{}" --tag "v${_dateutc}"
          sleep 2
          sudo /bin/rm -fr /home/.tmp
